// -----------------------------------------------------------------------------
//   _____ __  __                  _
//  / ____|  \/  |                | |
// | |    | \  / | ___  _ __ _ __ | |__
// | |    | |\/| |/ _ \| '__| '_ \| '_ \
// | |____| |  | | (_) | |  | |_) | | | |
//  \_____|_|  |_|\___/|_|  | .__/|_| |_|
//                          | |                    
//                          |_|                    
//
// The Complete Morph - public source release
// -----------------------------------------------------------------------------
//
// Originally released under a custom license.
// This historical re-release is provided under the MIT License.
// See the LICENSE file in the repo root for details.
//
// https://github.com/nettlep
//
// -----------------------------------------------------------------------------
//
// Notes about this software:
//
// CMorph generates high quality (even by today's standards) two-dimensional
// morphs from two static input images. It was written for DOS a number of years
// ago, using the Watcom compiler, back before C++ was the rage.
//
// Some of this source is ugly, but it should all be fairly readable.
//
// You will not be able to simply compile this program into an EXE because not
// all components of the program exist (there are some other libraries that are
// required, but are unavailable for public release at this time.) These missing
// libraries are the Int86 lib (DOS software interrupts), FLIC lib (animations)
// and the Image lib (loading/saving of image files.)
//
// This source code is best viewed with 4-character tabs.
//
// -----------------------------------------------------------------------------
/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
  ±                                                                          ±
  ±   Copyright (c) 1994 Paul D. Nettle.  All Rights Reserved.               ±
  ±                                                                          ±
  ±   [CMTYPES.H   ] - CMorph Types                                          ±
  ±                                                                          ±
  ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

typedef struct Mesh
{

   short HorizRes;
   short VertRes;
   float HorizList[MESH_SIZE][MESH_SIZE];
   float VertList[MESH_SIZE][MESH_SIZE];
              
} *MESH, _MESH;

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

#ifndef  uchr
typedef  unsigned char        UCHAR;
#define  uchr
#endif

#ifndef  ushrt
typedef  unsigned short int   USHORT;
#define  ushrt
#endif

#ifndef  ulng
typedef  unsigned long  int   ULONG;
#define  ulng
#endif

#ifndef  chr
typedef  char                 CHAR;
#define  chr
#endif

#ifndef  shrt
typedef  short int            SHORT;
#define  shrt
#endif

#ifndef  lng
typedef  long  int            LONG;
#define  lng
#endif

#ifndef  flot
typedef  float                FLOAT;
#define  flot
#endif

#ifndef  dubl
typedef  double               DOUBLE;
#define  dubl
#endif

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

typedef struct GrInfo
{

   short ResX, ResY;
   short MaxX, MaxY;
   short CenX, CenY;
   short Colors;
   short Mode;

} *GINFO, _GINFO;

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

typedef struct Rect
{

   short Left;
   short Top;
   short Right;
   short Bottom;
              
} *RECT, _RECT;

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

typedef struct Button
{

   _RECT Rect;
   int   Type;
   int   State;
   char  Title[128];

} *BUTTON, _BUTTON;

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

typedef struct Prompt
{

   _RECT Rect;
   int   WidthChars;

} *PROMPT, _PROMPT;

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

typedef struct DB_Element
{

   _RECT Rect;
   int   Type;
   int   *PromptVal;
   char  *PromptString;
   void  *Object;

} *DB_ELEMENT, _DB_ELEMENT;

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

typedef struct Dialog
{

   char  Title[128];
   _DB_ELEMENT Elements[];

} *DIALOG, _DIALOG;

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
  ±   [CMTYPES.H   ] - End Of File                                           ±
  ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/
